### ISSUE TITLE
Sample Kubernetes DaemonSet

### ISSUE THREAD

**Issue by alijaza** [bsycorp/log-forwarder#3]
Hello, do you have any sample K8S yaml files you can share for your project? I'm using fluentd currently, and running into some memory consumption issues similar to those you reported.

**Comment by nhoughto** [comment]
So we don't actually run this as a daemonset, we run it directly on the host, so i don't have a ready made example for you, but it should be fairly easy to translate the `docker run` command into a daemonset config. The important bits to map are the `-e` to environment variables, and the `-v` into hostPath volume mounts.

SystemD example is in the readme: https://github.com/bsycorp/log-forwarder

Happy to help if you get stuck.

**Comment by nhoughto** [comment]
Ended up writing this for to test it out, so thought may as well share it:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: log-fwd
spec:
  template:
    metadata:
      labels:
        app: log-fwd
      name: log-fwd
    spec:
      hostNetwork: true
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
      containers:
      - image: bsycorp/log-forwarder:latest
        imagePullPolicy: Always
        name: log-fwd
        env:
          - name: SUMO_SOURCE_CATEGORY
            value: category
          - name: SUMO_SOURCE_NAME
            value: source_name
          - name: SUMO_TRUSTED_TIMESTAMP_COLLECTOR_URL
            value: https://collectors.au.sumologic.com/receiver/v1/http/...
          - name: SUMO_UNTRUSTED_TIMESTAMP_COLLECTOR_URL
            value: https://collectors.au.sumologic.com/receiver/v1/http/...
          - name: SUMO_EXCLUDE_SOURCE_CATEGORIES
            value: log-fwd
        volumeMounts:
          - name: docker-volume
            mountPath: /var/run/docker.sock
          - name: etc-volume
            mountPath: /etc
          - name: journal-volume
            mountPath: /var/log/journal
            readOnly: true
          - name: state-volume
            mountPath: /var/lib/log-forwarder
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: docker-volume
        - hostPath:
            path: /etc
          name: etc-volume
        - hostPath:
            path: /var/log/journal
          name: journal-volume
        - hostPath:
            path: /var/lib/log-forwarder
          name: state-volume
```
